ad_computers = {
    "name": {"type": 'str'},
    "host_name": {"type": 'str'},
    "dnsHostName": {"type": "str", "default": "-"},
    "osname": {"type": "str"},
    "OperatingSystemVersion": {"type": "str"},
    "distinguishedName": {"type": "str"},
    "samAccountName": {"type": "str"},
    "enabled": {'type': 'bool'},
    "lastLogonTimestamp": {"type": 'str', 'convert': 'datetime'},
    "lastLogonDate": {'type': 'str', 'convert': 'datetime'},
    "whenCreated": {"type": 'str', 'convert': 'datetime'},
    "whenModified": {"type": 'str', 'convert': 'datetime'},
    "lockedOut": {"type": 'bool'},
    "passwordExpired": {"type": 'bool'},
    "passwordLastSet": {"type": 'str', 'convert': 'datetime'},
    "passwordNeverExpires": {"type": 'bool'},
    "passwordNotRequired": {"type": 'bool'},
    "domain": {'type': 'str'},
    "memberOf": {'type': 'list', 'default': []},
}

ad_users = {
    'lockedOut': {'type': 'bool'},
    'emailAddress': {'type': 'str', 'default': '-'},
    'department': {'type': 'str', 'default': '-'},
    'badLogonCount': {'type': 'int'},
    'passwordNeverExpires': {'type': 'bool'},
    'passwordExpired': {'type': 'bool'},
    'passwordNotRequired': {'type': 'bool'},
    'cannotChangePassword': {'type': 'bool'},
    'passwordLastSet': {'type': 'str', 'convert': 'datetime'},
    'name': {'type': 'str', 'default': '-'},
    'passwordExpireDate': {'type': 'str', 'convert': 'datetime'},
    'whenCreated': {'type': 'str', 'convert': 'datetime'},
    'whenModified': {'type': 'str', 'convert': 'datetime'},
    'samAccountName': {'type': 'str', 'default': '-'},
    'ouName': {'type': 'str', 'default': '-'},
    'enabled': {'type': 'bool'},
    'logonCount': {'type': 'int'},
    'domain': {'type': 'str', 'default': '-'},
    'accountExpireDate': {'type': 'str', 'convert': 'datetime'},
    'lastLogonTimestamp': {'type': 'str', 'convert': 'datetime'},
    'lastLogonDate': {'type': 'str', 'convert': 'datetime'},
    'memberOf': {'type': 'list', 'default': []},
    'office': {'type': 'str', 'default': '-'},
    "displayName": {'type': 'str', 'default': '-'},
    "accountLockoutTime": {'type': 'str', 'convert': 'datetime'},
    "lastbadPwdAttempt": {'type': 'str', 'convert': 'datetime'},
    "distinguishedName": {'type': 'str', 'default': '-'},
    "domainAdmin": {'type': 'bool'},
    "enterpriseAdmin": {'type': 'bool'},
    "buildInAdmin": {'type': 'bool'},
    "homeDrive": {'type': 'str', 'default': '-'},
    "homeDirectory": {'type': 'str', 'default': '-'},
}

ad_gpo = {
    'displayName': {'type': 'str', 'default': '-'},
    'domain': {'type': 'str', 'default': '-'},
    'gpoModifiedTime': {'type': 'str', 'convert': 'datetime'},
    'linkedTo': {'type': 'list', 'default': []},
    'gpoCreatedTime': {'type': 'str', 'convert': 'datetime'},
    'guid': {'type': 'str'},
    'gpoStatus': {'type': 'str'},
    'path': {'type': 'str', 'default': '-'},
    'name': {'type': 'str', 'default': '-'}
}

ad_groups = {
    'canonicalName': {'type': 'str', 'default': '-'},
    "managedBy": {'type': 'str', 'default': '-'},
    "samAccountName": {'type': 'str', 'default': '-'},
    "domain": {'type': 'str', 'default': '-'},
    "category": {'type': 'str', 'default': '-'},
    "groupCreated": {'type': 'str', 'convert': 'datetime'},
    "name": {'type': 'str', 'default': '-'},
    "commonName": {'type': 'str', 'default': '-'},
    "distinguishedName": {'type': 'str', 'default': '-'},
    "scope": {'type': 'str', 'default': '-'},
    "ouName": {'type': 'str', 'default': '-'},
    "isCriticalSystemObj": {'type': 'bool'},
    "empty": {'type': 'bool'},
    "members": {'type': 'list', "default": []},
    "memberOf": {'type': 'list', 'default': []},
}

ad_ou = {
    'managedBy': {'type': 'str'},
    'domain': {'type': 'str'},
    'ouName': {'type': 'str'},
    'linkedGPO': {'type': 'list'},
    'empty': {'type': 'bool'},
    'ouCreated': {'type': 'str', 'convert': 'datetime'},
    'ouModified': {'type': 'str', 'convert': 'datetime'},
    "distinguishedName": {'type': 'str', 'default': '-'},
    "guid": {'type': 'str', 'default': '-'},
    "gpLinks": {'type': 'list', 'default': []},
    "isCriticalSystemObj": {'type': 'bool'},
}

ad_passwordpolicy = {
    "complexityEnabled": {"type": "bool"},
    "distinguishedName": {"type": "str", "default": "-"},
    "lockoutDuration": {"type": "str", "default": "-"},
    "lockoutObservationWindow": {"type": "str", "default": "-"},
    "lockoutThreshold": {"type": "str", "default": "-"},
    "maxPasswordAge": {"type": "int"},
    "minPasswordAge": {"type": "int"},
    "minPasswordLength": {"type": "int"},
    "passwordHistoryCount": {"type": "int"},
    "reversibleEncryptionEnabled": {"type": "bool"},
    "domain": {'type': 'str'},
}

fsmo_roles = {
    "role": {"type": "str"},
    "domain": {'type': 'str'},
}

